[variables]
PLAYWRIGHT_BROWSERS_PATH = "0"

[phases.setup]
nixPkgs = ["chromium", "glib", "nss", "nspr", "atk", "cups", "dbus", "gdk-pixbuf", "gtk3", "pango", "cairo"]

[phases.install]
cmds = [
    "python -m pip install -r requirements.txt",
    "playwright install chromium --with-deps"
]

[start]
cmd = "python main.py"
